services:
  db: 
    image: postgres
    volumes: 
      - ./data/db:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: bash -c "python manage.py makemigrations &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    links:
      - "db:db"

  